### ISSUE TITLE
The name of the country and data within historical data doesn't seem to update

### ISSUE THREAD

**Issue by asl97** [bufferhead-code/onthisday#3]
The name of the country and data within historical data doesn't seem to update

I changed the country to the first option, Afghanistan, but it still shows the data for Austria for the bottom text portions, the graph do update though.

![onthisday bufferhead com](https://github.com/bufferhead-code/onthisday/assets/4752645/39760c51-feef-4237-a4dc-65c6aef9391f)

PS: when I saw the youtube title, thumbnail and especially the opening line: `"running a database can get really expensive really fast"`, for a moment, I thought it was about abusing github action to host an actual database, which github itself seem to suggest it was possible but they also mention it's totally against their acceptable usage.

I am glad it was just merely hosting a database file, which can hardly even be call running a database to be honest, even if it does do over 200+ http requests per load/country.

**Comment by bufferhead-code** [comment]
thanks for the bug report, it should be fixed now.
